name: projeto_tcc_flutter
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  get: ^4.6.6
  flutter_clean_architecture: ^6.0.1

  flutter_localizations:
    sdk: flutter
  flutter_i18n: ^0.36.0
  provider: ^6.1.2
  equatable: ^2.0.5
  http: ^1.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/i18n/
